### PR TITLE
Fix: Reskin of project preview cards

### LINKED ISSUE #516: visual refresh of Projects cards
visual refresh according to this image: 
image

- [ ] Outline coulor: #E0E0E0 width: 1 pt; shadow : x:3 y:3 w:6 #000000 9%
- [ ] add Profile pictures of collaborating Organisation to card
- [ ] Icons in main colour
- [ ] add number of likes (once introduced in projects) and comments 
- [ ] add project type

### PR DESCRIPTION
**Pull request by JoshKornfeld**
## Description

Closes #516
This PR aims to reskin project preview cards according to the design given by the issue #516 and builds upon existing functionality in PR #668.

Backend: Modified seralizer to get collaborating organizations
Frontend:
- Changed miniorganizationpreviews from a square image to round avatar
- Added more spacing between each row of information
- Added box shadow
- Recolored icons to main theme color
- If a project has collaborating orgs, up to 2 will be shown on the card without their name. These icons will have a slim gray border.
- Added additional info to the card such as number of comments and number of likes and the project's status

## Before landing

1. PR has meaningful title
1. `yarn lint` passes (frontend)
1. `yarn format` passes (frontend)
1. `make format` passes (backend)

### CODE REVIEW

**Comment by ddhanesha** [comment]
Screenshot 2022-10-31 at 9 15 33 PM


@JoshKornfeld I am getting this error. You are assuming here that all projects will have parent organization but that is not necessary. We could have projects without an organization. Even tho you may see most projects are associated with an organization

**Review by ddhanesha — CHANGES_REQUESTED** [review]
Left a blocking comment

**Comment by JoshKornfeld** [comment]
Error should now be resolved. Removed the assumption that a project has a parent organization.

**Review by ddhanesha — APPROVED** [review]
Features are working as expected. Approved! Good job @JoshKornfeld

**Pull request merged**
