### PR TITLE
run 'black' in all files

### PR DESCRIPTION
**Pull request by positiveimpact**
## Description

Ran the code formatter `black` over all files in the backend. Now our code formatting should all be the same.

## Test plan

Simply see if the website still works and look for any potentially breaking changes that the formatter made. Overall it should be quite safe.

### CODE REVIEW

**Review by piperchester — APPROVED** [review]
LGTM! I did some basic confidence testing locally and didn't see any issues. We should ensure that black formatting is enforced on CI going forward.

**Comment by ddhanesha** [comment]
@positiveimpact there are no code changes in this PR right? Also can you resolve conflicts?

**Comment by ddhanesha** [comment]
@positiveimpact I think we should not use this library right now for code formatting. I will create a separate PR with latest code. Closing this PR.

**Comment by piperchester** [comment]
> @positiveimpact I think we should not use this library right now for code formatting. I will create a separate PR with latest code. Closing this PR.

What was your thinking on not using black @ddhanesha?

**Pull request closed without merging**
