### PR TITLE
fix: hide header on scroll down and show on scroll up

### LINKED ISSUE #727: Mobile: Hide header when scrolling down, make header smaller in General
**Is your feature request related to a problem? Please describe.**
The header on mobile is really huge and takes up way too much space. 

**Describe the solution you'd like**
The header should be made smaller and should disappear when scrolling down and then reappear when scrolling up

**Describe alternatives you've considered**
The header could just be made smaller when scrolling down but not bigger when scrolling up

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
## Description
Resolve #727

Hide header(navbar) when the user scrolls down on mobile and shows when the user scrolls up. Larger screens remain the same as they were.

## Test plan

- Go to [climate connect](https://climateconnect.earth/)
- Reduce your window size if you're not on mobile.
- Scroll down(navbar should be hidden at this point)
- scroll up(navbar shows up)

**On Scroll down**

Screenshot (239)

**On Scroll up**

Screenshot (240)

## Before landing

1. PR has meaningful title
2. `yarn lint` passes (frontend)
3. `yarn format` passes (frontend) -- No, I got the below error Instead tho I follow code pattern to format

> yarn run v1.22.17
warning ..\..\..\package.json: No license field
$ prettier --write '**/*.{js,jsx,json,md}'
[error] No files matching the pattern were found: "'**/*.{js,jsx,json,md}'".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

5. `make format` passes (backend)

## Extra Steps Taken

- Remove fixed height given to header. I removed it cause it's giving extra height to the header element.
- Reduce padding of header element on mobile.
- Reduce logo size on mobile.

### CODE REVIEW

**Review by positiveimpact — CHANGES_REQUESTED** [review]
Thanks for contributing again! The mobile header looks really great now. However showing the scrollbar again when scrolling up doesn't seem to be working. I tested while logged out on the `/` page where the header is usually fixed on the top. It didn't reappear when scrolling up again and the reason seems to be that the value of `lastScrollY` never updates (in my video it's always 0). I think this is because you're doing 2 state updates in the useEffect hook. 
So this would still need to be resolved, otherwise it looks good!
header_not_showing_on_scroll_up

**Comment by Olaleye-Blessing** [comment]
Updated, you can check now.

**Review by positiveimpact — COMMENTED** [review]
LGTM now! Once you merge master this is ready to merge! :) 
And sorry for the late review, I was quite busy.

**Comment by Olaleye-Blessing** [comment]
> LGTM now! Once you merge master this is ready to merge! :) And sorry for the late review, I was quite busy.

You mean I should fix the conflict by merging to master, then create a pull request right?

**Comment by positiveimpact** [comment]
> > LGTM now! Once you merge master this is ready to merge! :) And sorry for the late review, I was quite busy.
> 
> You mean I should fix the conflict by merging to master, then create a pull request right?

I mean merging master into this branch and resolving the conflict. Then we can merge this branch into master

**Review by positiveimpact — APPROVED** [review]
LGTM! :) Great work :ok_hand:

**Pull request merged**
