### PR TITLE
Feature: Adapt Project Page To Event Calendar

### PR DESCRIPTION
**Pull request by positiveimpact**
## What and Why

This PR makes the necessary adjustments to the project page to account for different types of projects.

## Detailled changes
- Store project types in a constant instead of the database as suggested by @ddhanesha 
- Adapt terms in static texts to project type, e.g. "Event Description" instead of "Project Description" on events
- Correctly display detailled location including additional info
- Display start and end date of events in the summary section -> display date differently depending on language
- Display project type in the summary section
- Don't show project status anymore
- Don't show project dates for events anymore
- Made admin buttons into icon buttons on mobile
- Polished parent organization display
- Ran 'yarn format'
- Cleaned up code by typing some functions, isolating some components and cutting down on passed through arguments

## Testing Guide
Create one project of each project type and see if they are displayed correctly. Also test this when logged out.

## Screenshots
Screenshot from 2023-08-17 11-31-05
Screenshot from 2023-08-17 11-37-15

### CODE REVIEW

**Comment by ddhanesha** [comment]
@positiveimpact at the last step of creating the project. I am getting this error:

```python
Internal Server Error: /api/create_project/
Traceback (most recent call last):
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspaces/climateconnect/backend/organization/views/project_views.py", line 317, in post
    translations_object = get_project_translations(request.data)
  File "/workspaces/climateconnect/backend/organization/utility/project.py", line 149, in get_project_translations
    return get_translations(texts, data["translations"], data["source_language"])
  File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 171, in get_translations
    translated_text_object = translate_text(
  File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 111, in translate_text
    and get_locale(translation["detected_source_language"]) == target_locale
KeyError: 'detected_source_language'
"POST /api/create_project/ HTTP/1.1" 500 146235
DEEPL_API_KEY not set, not translating
DEEPL_API_KEY not set, not translating
DEEPL_API_KEY not set, not translating
Internal Server Error: /api/create_project/
Traceback (most recent call last):
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspaces/climateconnect/backend/organization/views/project_views.py", line 317, in post
    translations_object = get_project_translations(request.data)
  File "/workspaces/climateconnect/backend/organization/utility/project.py", line 149, in get_project_translations
    return get_translations(texts, data["translations"], data["source_language"])
  File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 171, in get_translations
    translated_text_object = translate_text(
  File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 111, in translate_text
    and get_locale(translation["detected_source_language"]) == target_locale
KeyError: 'detected_source_language'
```

I am not sure if this related to this PR or something else. But I can see UI as expected.

**Comment by ddhanesha** [comment]
Screenshot 2023-08-19 at 4 22 16 PM

**Comment by ddhanesha** [comment]
> @positiveimpact at the last step of creating the project. I am getting this error:
> 
> ```python
> Internal Server Error: /api/create_project/
> Traceback (most recent call last):
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
>     return callback(request, *args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
>     return view_func(*args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/usr/lib/python3.9/contextlib.py", line 79, in inner
>     return func(*args, **kwds)
>   File "/workspaces/climateconnect/backend/organization/views/project_views.py", line 317, in post
>     translations_object = get_project_translations(request.data)
>   File "/workspaces/climateconnect/backend/organization/utility/project.py", line 149, in get_project_translations
>     return get_translations(texts, data["translations"], data["source_language"])
>   File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 171, in get_translations
>     translated_text_object = translate_text(
>   File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 111, in translate_text
>     and get_locale(translation["detected_source_language"]) == target_locale
> KeyError: 'detected_source_language'
> "POST /api/create_project/ HTTP/1.1" 500 146235
> DEEPL_API_KEY not set, not translating
> DEEPL_API_KEY not set, not translating
> DEEPL_API_KEY not set, not translating
> Internal Server Error: /api/create_project/
> Traceback (most recent call last):
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
>     return callback(request, *args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
>     return view_func(*args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/usr/lib/python3.9/contextlib.py", line 79, in inner
>     return func(*args, **kwds)
>   File "/workspaces/climateconnect/backend/organization/views/project_views.py", line 317, in post
>     translations_object = get_project_translations(request.data)
>   File "/workspaces/climateconnect/backend/organization/utility/project.py", line 149, in get_project_translations
>     return get_translations(texts, data["translations"], data["source_language"])
>   File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 171, in get_translations
>     translated_text_object = translate_text(
>   File "/workspaces/climateconnect/backend/climateconnect_api/utility/translation.py", line 111, in translate_text
>     and get_locale(translation["detected_source_language"]) == target_locale
> KeyError: 'detected_source_language'
> ```
> 
> I am not sure if this related to this PR or something else. But I can see UI as expected.

Solved this error. But got another one,

```python
Internal Server Error: /api/create_project/
Traceback (most recent call last):
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/workspaces/climateconnect/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspaces/climateconnect/backend/organization/views/project_views.py", line 333, in post
    project = create_new_project(request.data, source_language)
  File "/workspaces/climateconnect/backend/organization/utility/project.py", line 24, in create_new_project
    project_type = ProjectTypesChoices[data["type"]]
KeyError: 'type'
```

**Comment by positiveimpact** [comment]
Good catch, this seems to happen when you don't change the project type choice in the first step of share project. I merged a fix, now it should work

**Pull request merged**
